### ISSUE TITLE
Accessing the response picker is very slow for users with WS level permission only

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backlog#50] opened 2022-11-28 11:27 UTC
**Requirements**
I've noticed that there is a significant difference in load time for the list of health facilities depending on whether a user has WS level or admin permissions. With my own account the response picker loads within less than 2sec while for users with WS level permission it takes 10+ seconds. 

This might expalin why we have been receiving an increasing number of users complaing about the the long load times. 

**Proposed solution**
It appears the system is validating the permissions everytime a user is re-loading a workspace. Would it be possilbe that permissions are only validated once and cached for the rest of the session? 

**Additional context**
If there are any tempoaray fixes that we can implement to improve the load time, please let's discuss in the next meeting. This is of relatively high importance as it has significant impact on data entry particulalry in areas where internet access is already a challenge.

**Comment by luna404** [comment] 2022-11-29 09:07
user id: 17945 or 17996
workspace:  https://herams.org/workspace/11905/limesurvey

**Comment by SamMousa** [comment] 2022-11-29 13:15
A large part of the issue is the fact that there are ~500 access requests open and the system needs to verify for each one whether the current user can respond.
Any chance we can clean them up?

**Comment by SamMousa** [comment] 2022-11-29 14:03
Rejected all old access requests; it's a lot quicker now. Please have a look @luna404

**Comment by luna404** [comment] 2022-11-29 15:40
That's a huge difference even with my own profile.
Debug mode is still on, is that on purpose?

**Comment by SamMousa** [comment] 2022-11-29 15:43
No just until you confirmed (only admins have access to that).
Closing this

**Closed by SamMousa** 2022-11-29 15:43 UTC
